import type { Octokit } from "@octokit/core";
import type { ReviewFinding } from "../reviewers/types.js";
import type { PostMode } from "../config/schema.js";
import { logger } from "../utils/logger.js";

interface PostOptions {
  octokit: Octokit;
  owner: string;
  repo: string;
  pullNumber: number;
  commitSha: string;
  findings: ReviewFinding[];
  postAs: PostMode;
}

/**
 * Post the aggregated review findings back to the PR.
 */
export async function postFindings(opts: PostOptions): Promise<void> {
  const { octokit, owner, repo, pullNumber, commitSha, findings, postAs } =
    opts;

  if (findings.length === 0) {
    await postSummaryComment(octokit, owner, repo, pullNumber, []);
    return;
  }

  if (postAs === "review" || postAs === "both") {
    await postReview(octokit, owner, repo, pullNumber, commitSha, findings);
  }

  if (postAs === "comment" || postAs === "both") {
    await postSummaryComment(octokit, owner, repo, pullNumber, findings);
  }
}

// ── Post as a PR Review with inline comments ─────────────────────────

async function postReview(
  octokit: Octokit,
  owner: string,
  repo: string,
  pullNumber: number,
  commitSha: string,
  findings: ReviewFinding[]
): Promise<void> {
  // Split findings: ones with line info go inline, rest go in the body
  const inline = findings.filter((f) => f.file && f.line);
  const general = findings.filter((f) => !f.file || !f.line);

  const body = formatReviewBody(general, findings.length);

  const comments = inline.map((f) => ({
    path: f.file!,
    line: f.line!,
    body: formatInlineComment(f),
  }));

  try {
    await octokit.request(
      "POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews",
      {
        owner,
        repo,
        pull_number: pullNumber,
        commit_id: commitSha,
        event: "COMMENT",
        body,
        comments,
      }
    );
    logger.info(
      { pullNumber, inlineCount: comments.length },
      "Posted PR review"
    );
  } catch (err) {
    logger.error({ err }, "Failed to post PR review — falling back to comment");
    await postSummaryComment(octokit, owner, repo, pullNumber, findings);
  }
}

// ── Post as a single issue comment ───────────────────────────────────

async function postSummaryComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  pullNumber: number,
  findings: ReviewFinding[]
): Promise<void> {
  let body: string;

  if (findings.length === 0) {
    body =
      "## 🤖 AI Code Review\n\nAll clear — no issues found across all reviewers. ✅";
  } else {
    body = formatFullSummary(findings);
  }

  await octokit.request(
    "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
    { owner, repo, issue_number: pullNumber, body }
  );

  logger.info({ pullNumber }, "Posted summary comment");
}

// ── Formatters ───────────────────────────────────────────────────────

function severityEmoji(s: ReviewFinding["severity"]): string {
  const map = { critical: "🔴", high: "🟠", medium: "🟡", low: "🔵", info: "ℹ️" };
  return map[s];
}

function formatInlineComment(f: ReviewFinding): string {
  return `${severityEmoji(f.severity)} **${f.severity.toUpperCase()}** — _${f.reviewer}_\n\n${f.message}`;
}

function formatReviewBody(
  general: ReviewFinding[],
  totalCount: number
): string {
  const lines = [
    `## 🤖 AI Code Review — ${totalCount} finding(s)\n`,
  ];

  if (general.length > 0) {
    lines.push("### General findings\n");
    for (const f of general) {
      lines.push(
        `- ${severityEmoji(f.severity)} **${f.severity.toUpperCase()}** [${f.reviewer}]: ${f.message}`
      );
    }
  }

  lines.push(
    "\n---\n_Review generated by [ai-code-reviewer](https://github.com/apps/ai-code-reviewer)_"
  );
  return lines.join("\n");
}

function formatFullSummary(findings: ReviewFinding[]): string {
  // Group by reviewer
  const grouped = new Map<string, ReviewFinding[]>();
  for (const f of findings) {
    const list = grouped.get(f.reviewer) ?? [];
    list.push(f);
    grouped.set(f.reviewer, list);
  }

  const lines = [`## 🤖 AI Code Review — ${findings.length} finding(s)\n`];

  for (const [reviewer, items] of grouped) {
    lines.push(`### ${reviewer}\n`);
    for (const f of items) {
      const loc = f.file ? `\`${f.file}${f.line ? `:${f.line}` : ""}\`` : "";
      lines.push(
        `- ${severityEmoji(f.severity)} **${f.severity.toUpperCase()}** ${loc ? `(${loc})` : ""}: ${f.message}`
      );
    }
    lines.push("");
  }

  lines.push(
    "---\n_Review generated by [ai-code-reviewer](https://github.com/apps/ai-code-reviewer)_"
  );
  return lines.join("\n");
}
