/**
 * GitHub App manifest flow — creates the app in one click.
 *
 * Usage: npx tsx scripts/setup-app.ts
 *
 * 1. Starts a local server on port 3456
 * 2. Opens the browser to GitHub's "create app from manifest" page
 * 3. You click "Create GitHub App"
 * 4. GitHub redirects back with a code
 * 5. We exchange it for credentials and save them
 */

import http from "node:http";
import fs from "node:fs";
import { execSync } from "node:child_process";

const PORT = 3456;
const CALLBACK = `http://localhost:${PORT}/callback`;

const manifest = {
  name: "AI Code Reviewer",
  url: "https://github.com/rajeshkumar-pm/ai-code-reviewer",
  hook_attributes: {
    url: "https://smee.io/ai-code-reviewer-temp", // placeholder — updated after smee setup
    active: true,
  },
  redirect_url: CALLBACK,
  public: false,
  default_permissions: {
    pull_requests: "write",
    contents: "read",
    metadata: "read",
  },
  default_events: ["pull_request"],
};

// ── HTML page that auto-submits the manifest to GitHub ───────────────
function landingPage(): string {
  return `
    <html><body>
      <h2>Creating GitHub App...</h2>
      <p>If you're not redirected, click the button below.</p>
      <form id="f" method="post" action="https://github.com/settings/apps/new">
        <input type="hidden" name="manifest" value='${JSON.stringify(manifest)}'>
        <button type="submit">Create GitHub App</button>
      </form>
      <script>document.getElementById('f').submit();</script>
    </body></html>
  `;
}

// ── Start server and handle the flow ─────────────────────────────────
const server = http.createServer(async (req, res) => {
  const url = new URL(req.url!, `http://localhost:${PORT}`);

  if (url.pathname === "/") {
    res.writeHead(200, { "Content-Type": "text/html" });
    res.end(landingPage());
    return;
  }

  if (url.pathname === "/callback") {
    const code = url.searchParams.get("code");
    if (!code) {
      res.writeHead(400, { "Content-Type": "text/plain" });
      res.end("Missing code parameter");
      return;
    }

    try {
      // Exchange code for app credentials
      const response = await fetch(
        `https://api.github.com/app-manifests/${code}/conversions`,
        {
          method: "POST",
          headers: {
            Accept: "application/vnd.github+json",
          },
        }
      );

      if (!response.ok) {
        const err = await response.text();
        throw new Error(`GitHub API error: ${response.status} — ${err}`);
      }

      const data = (await response.json()) as {
        id: number;
        slug: string;
        pem: string;
        webhook_secret: string;
        client_id: string;
        client_secret: string;
        html_url: string;
      };

      // Save the private key
      const pemPath = "private-key.pem";
      fs.writeFileSync(pemPath, data.pem);
      fs.chmodSync(pemPath, 0o600);

      // Create .env from the credentials
      const envContent = [
        `# ── GitHub App (auto-generated by setup script) ──────`,
        `GITHUB_APP_ID=${data.id}`,
        `GITHUB_PRIVATE_KEY_PATH=./private-key.pem`,
        `GITHUB_WEBHOOK_SECRET=${data.webhook_secret}`,
        ``,
        `# ── AI Provider Keys (fill these in) ─────────────────`,
        `ANTHROPIC_API_KEY=`,
        `OPENAI_API_KEY=`,
        `GEMINI_API_KEY=`,
        ``,
        `# ── Server ───────────────────────────────────────────`,
        `PORT=3000`,
        `LOG_LEVEL=info`,
        ``,
        `# ── Dev ──────────────────────────────────────────────`,
        `# SMEE_URL=  (will be set up next)`,
      ].join("\n");

      fs.writeFileSync(".env", envContent);

      console.log("\n✅ GitHub App created successfully!\n");
      console.log(`   App name:  ${data.slug}`);
      console.log(`   App ID:    ${data.id}`);
      console.log(`   App URL:   ${data.html_url}`);
      console.log(`   Client ID: ${data.client_id}`);
      console.log(`\n   Private key saved to: ${pemPath}`);
      console.log(`   .env file created with credentials\n`);
      console.log(`\n👉 Next: Install the app on your repos at:`);
      console.log(`   ${data.html_url}/installations/new\n`);

      res.writeHead(200, { "Content-Type": "text/html" });
      res.end(`
        <html><body>
          <h2>✅ GitHub App created!</h2>
          <p><strong>App:</strong> ${data.slug} (ID: ${data.id})</p>
          <p><strong>Private key</strong> saved to <code>private-key.pem</code></p>
          <p><strong>.env</strong> file created with credentials</p>
          <p>You can close this tab now.</p>
          <p><a href="${data.html_url}/installations/new">👉 Install the app on your repositories</a></p>
        </body></html>
      `);
    } catch (err) {
      console.error("❌ Failed to create app:", err);
      res.writeHead(500, { "Content-Type": "text/plain" });
      res.end(`Error: ${err}`);
    }

    // Shutdown after a brief delay
    setTimeout(() => {
      server.close();
      process.exit(0);
    }, 1000);
    return;
  }

  res.writeHead(404);
  res.end("Not found");
});

server.listen(PORT, () => {
  const url = `http://localhost:${PORT}`;
  console.log(`\n🚀 Opening browser to create GitHub App...\n`);
  console.log(`   If it doesn't open, go to: ${url}\n`);

  // Open browser
  try {
    execSync(`open "${url}"`);
  } catch {
    // Non-macOS fallback
    try {
      execSync(`xdg-open "${url}"`);
    } catch {
      console.log("   (Could not open browser — please open the URL manually)");
    }
  }
});
